### ISSUE TITLE
`make help` fails on macOS

### ISSUE THREAD

**Issue by kaakaa** [mattermost/mattermost-plugin-sample#26]
`make help` fails on macOS, because `tac` is not default command on macOS.

```
$ make help
/bin/sh: tac: command not found
```

@lieut-data 
As you said in [this comments](https://github.com/mattermost/mattermost-plugin-sample/pull/19#issuecomment-436811575), would you like to replace `tac` with `awk` for `make help`?
I think that `awk` is more compatible than `tac` for many os.

**Comment by lieut-data** [comment]
Ah, good catch, @kaakaa -- I'm guessing I got `tac` via some of the development tooling I use with Mattermost.

If https://unix.stackexchange.com/questions/9356/how-can-i-print-lines-from-file-backwards-without-using-tac is accurate, we can replace `tac` with `sed '1!G;h;$!d'`.

@kaakaa, would you be willing to test that and submit a PR if it works as advertised?
