### ISSUE TITLE
Can't upload plugin via API.

### ISSUE THREAD

**Issue by harisibrahimkv** [mattermost/mattermost-plugin-sample#4]
```
➜  g-plugin git:(master) ✗ export MM_SERVICESETTINGS_SITEURL=http://localhost:8065
➜  g-plugin git:(master) ✗ export MM_ADMIN_USERNAME=hobbes
➜  g-plugin git:(master) ✗ export MM_ADMIN_PASSWORD=building_character
➜  g-plugin git:(master) ✗ make deploy
Installing plugin via API
http --print b --check-status http://localhost:8065/api/v4/users/me || ( \
	    TOKEN=`http --print h POST http://localhost:8065/api/v4/users/login login_id=hobbes password=building_character | grep Token | cut -f2 -d' '` && \
	    http --print b GET http://localhost:8065/api/v4/users/me Authorization:"Bearer $TOKEN" \
	)
{
    "detailed_error": "",
    "id": "api.context.session_expired.app_error",
    "message": "Invalid or expired session, please login again.",
    "request_id": "mnmrma8wnpb4mnbubfct568whc",
    "status_code": 401
}

{
    "allow_marketing": true,
    "auth_data": "",
    "auth_service": "",
    "create_at": 1532409647831,
    "delete_at": 0,
    "email": "a@a.com",
    "first_name": "",
    "id": "96kjh8ttpin1zj58hd5utgnfca",
    "last_name": "",
    "last_password_update": 1532409647831,
    "locale": "en",
    "nickname": "",
    "notify_props": {
        "channel": "true",
        "comments": "never",
        "desktop": "mention",
        "desktop_sound": "true",
        "email": "true",
        "first_name": "false",
        "mention_keys": "hobbes,@hobbes",
        "push": "mention",
        "push_status": "away"
    },
    "position": "",
    "roles": "system_admin system_user",
    "timezone": {
        "automaticTimezone": "",
        "manualTimezone": "",
        "useAutomaticTimezone": "true"
    },
    "update_at": 1532604589454,
    "username": "hobbes"
}

http --print b DELETE http://localhost:8065/api/v4/plugins/g-plugin
{
    "detailed_error": "",
    "id": "api.context.session_expired.app_error",
    "message": "Invalid or expired session, please login again.",
    "request_id": "tbtxjs3xdfd19xgyanawh6u47h",
    "status_code": 401
}

http --print b --check-status --form POST http://localhost:8065/api/v4/plugins plugin@dist/g-plugin.tar.gz && \
	    http --print b POST http://localhost:8065/api/v4/plugins/g-plugin/enable

http: error: ConnectionError: ('Connection aborted.', BrokenPipeError(32, 'Broken pipe')) while doing POST request to URL: http://localhost:8065/api/v4/plugins
make: *** [deploy] Error 1
```
Here is my login attempt:
```
➜  g-plugin git:(master) ✗ http --print h POST http://localhost:8065/api/v4/users/login login_id=hobbes password=build_character
HTTP/1.1 200 OK
Content-Length: 643
Content-Type: application/json
Date: Sun, 05 Aug 2018 14:24:21 GMT
Set-Cookie: MMAUTHTOKEN=dc54xredjbywug5xx8kh7x9cqy; Path=/; Expires=Tue, 04 Sep 2018 14:24:21 GMT; Max-Age=2592000; HttpOnly
Set-Cookie: MMUSERID=96kjh8ttpin1zj58hd5utgnfca; Path=/; Expires=Tue, 04 Sep 2018 14:24:21 GMT; Max-Age=2592000
Token: dc54xredjbywug5xx8kh7x9cqy
X-Request-Id: gsxnbz7t1p8b8gf1rgjy4zd3xh
X-Version-Id: 5.1.0.5.1.0.6a280dd4b379e3dff0eca57ea893c010.false
```
Seems like I am missing something obvious...

**Comment by Hanzei** [comment]
Can confirm

**Comment by scottleedavis** [comment]
I am also getting the same result.  Can't upload via api.  Here is my output from the command make deploy

`
Installing plugin via API
http --print b --check-status http://127.0.0.1:8065/api/v4/users/me || ( \
	    TOKEN=`http --print h POST http://127.0.0.1:8065/api/v4/users/login login_id=skawtus password=iw2lsf | grep Token | cut -f2 -d' '` && \
	    http --print b GET http://127.0.0.1:8065/api/v4/users/me Authorization:"Bearer $TOKEN" \
	)
{
    "detailed_error": "UserRequired",
    "id": "api.context.session_expired.app_error",
    "message": "Invalid or expired session, please login again.",
    "request_id": "n59mbbqs63ghf8tb7mpdb9b8xh",
    "status_code": 401
}

{
    "allow_marketing": true,
    "auth_data": "",
    "auth_service": "",
    "create_at": 1534189461031,
    "delete_at": 0,
    "email": "skawtus@gmail.com",
    "first_name": "",
    "id": "49amhc9kh3yn8nnfrm9cygwdar",
    "last_name": "",
    "last_password_update": 1534189461031,
    "locale": "en",
    "nickname": "",
    "notify_props": {
        "channel": "true",
        "comments": "never",
        "desktop": "mention",
        "desktop_sound": "true",
        "email": "true",
        "first_name": "false",
        "mention_keys": "skawtus,@skawtus",
        "push": "mention",
        "push_status": "away"
    },
    "position": "",
    "roles": "system_admin system_user",
    "timezone": {
        "automaticTimezone": "America/Los_Angeles",
        "manualTimezone": "",
        "useAutomaticTimezone": "true"
    },
    "update_at": 1534190567640,
    "username": "skawtus"
}

http --print b DELETE http://127.0.0.1:8065/api/v4/plugins/io.github.mattermost-plugin-remind
{
    "detailed_error": "UserRequired",
    "id": "api.context.session_expired.app_error",
    "message": "Invalid or expired session, please login again.",
    "request_id": "48n5yh1ssjd9pbxn47yr9pozua",
    "status_code": 401
}

http --print b --check-status --form POST http://127.0.0.1:8065/api/v4/plugins plugin@dist/io.github.mattermost-plugin-remind.tar.gz && \
	    http --print b POST http://127.0.0.1:8065/api/v4/plugins/io.github.mattermost-plugin-remind/enable

http: error: ConnectionError: ('Connection aborted.', BrokenPipeError(32, 'Broken pipe')) while doing POST request to URL: http://127.0.0.1:8065/api/v4/plugins
make: *** [deploy] Error 1
`

Would be great if this worked before the hackathon on thursday & friday!  :)

**Comment by scottleedavis** [comment]
After some investigation, the makefile needs to be fixed.  the `TOKEN` variable does not have visibility in scope outside its evaluation inside '(' & ')'. 
Further more that TOKEN needs to be added to subsequent request as a the endpoints are expecting an 'Authorization' header.
Its late and I am headed to bed.  I'll try taking a stab at fixing the makefile tomorrow.

> 
> 	@echo "Installing plugin via API"
> 	http --print b --check-status $(MM_SERVICESETTINGS_SITEURL)/api/v4/users/me || ( \
> 	    TOKEN=`http --print h POST $(MM_SERVICESETTINGS_SITEURL)/api/v4/users/login login_id=$(MM_ADMIN_USERNAME) password=$(MM_ADMIN_PASSWORD) | grep Token | cut -f2 -d' '` && \
> 	    http --print b GET $(MM_SERVICESETTINGS_SITEURL)/api/v4/users/me Authorization:"Bearer $$TOKEN"
> 	http --print b DELETE $(MM_SERVICESETTINGS_SITEURL)/api/v4/plugins/$(PLUGIN_ID)
> 	http --print b --check-status --form POST $(MM_SERVICESETTINGS_SITEURL)/api/v4/plugins plugin@dist/$(PLUGIN_ID).tar.gz && \
> 	    http --print b POST $(MM_SERVICESETTINGS_SITEURL)/api/v4/plugins/$(PLUGIN_ID)/enable
> else ifneq ($(wildcard ../mattermost-server/.*),)
> 	@echo "Installing plugin via filesystem. Server restart and manual plugin enabling required"
> 	tar -C ../mattermost-server/plugins -zxvf dist/$(PLUGIN_ID).tar.gz
> the TOKEN variable, does not have visibility outside the boolean statment e.g.

**Comment by cpanato** [comment]
great catch! doing the change
